// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.0
// source: protos/source.proto

package po

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义'数据源信息'结构
type SourceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 类型 字段 = 标识号
	Id       uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`         //名称
	Host     string `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`         //主机
	Port     uint32 `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`        //端口
	Username string `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"` //用户名
	Password string `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"` //密码
	Charset  string `protobuf:"bytes,7,opt,name=charset,proto3" json:"charset,omitempty"`   //字符串编码
	SlaveID  uint32 `protobuf:"varint,8,opt,name=slaveID,proto3" json:"slaveID,omitempty"`  //SlaveID
	Flavor   string `protobuf:"bytes,9,opt,name=flavor,proto3" json:"flavor,omitempty"`     // mysql or mariadb,默认mysql
	Status   uint32 `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`   //状态 0正常 1停用
}

func (x *SourceInfo) Reset() {
	*x = SourceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_source_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceInfo) ProtoMessage() {}

func (x *SourceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protos_source_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceInfo.ProtoReflect.Descriptor instead.
func (*SourceInfo) Descriptor() ([]byte, []int) {
	return file_protos_source_proto_rawDescGZIP(), []int{0}
}

func (x *SourceInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SourceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SourceInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *SourceInfo) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *SourceInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SourceInfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SourceInfo) GetCharset() string {
	if x != nil {
		return x.Charset
	}
	return ""
}

func (x *SourceInfo) GetSlaveID() uint32 {
	if x != nil {
		return x.SlaveID
	}
	return 0
}

func (x *SourceInfo) GetFlavor() string {
	if x != nil {
		return x.Flavor
	}
	return ""
}

func (x *SourceInfo) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_protos_source_proto protoreflect.FileDescriptor

var file_protos_source_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf4, 0x01, 0x0a, 0x0a, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x72,
	0x73, 0x65, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x72, 0x73,
	0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x6c, 0x61, 0x76, 0x65, 0x49, 0x44, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x6c, 0x61, 0x76, 0x65, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06,
	0x66, 0x6c, 0x61, 0x76, 0x6f, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6c,
	0x61, 0x76, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x0c, 0x5a, 0x0a,
	0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x70, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_protos_source_proto_rawDescOnce sync.Once
	file_protos_source_proto_rawDescData = file_protos_source_proto_rawDesc
)

func file_protos_source_proto_rawDescGZIP() []byte {
	file_protos_source_proto_rawDescOnce.Do(func() {
		file_protos_source_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_source_proto_rawDescData)
	})
	return file_protos_source_proto_rawDescData
}

var file_protos_source_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_source_proto_goTypes = []interface{}{
	(*SourceInfo)(nil), // 0: SourceInfo
}
var file_protos_source_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_source_proto_init() }
func file_protos_source_proto_init() {
	if File_protos_source_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_source_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_source_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_source_proto_goTypes,
		DependencyIndexes: file_protos_source_proto_depIdxs,
		MessageInfos:      file_protos_source_proto_msgTypes,
	}.Build()
	File_protos_source_proto = out.File
	file_protos_source_proto_rawDesc = nil
	file_protos_source_proto_goTypes = nil
	file_protos_source_proto_depIdxs = nil
}
